### ISSUE TITLE
Question about Module?

### ISSUE THREAD

**Issue by joeymisfit** [BillyAB/WHMCS-Discord-Notification-Module#1]
Is it possible to add under notification settings for Discord a way to bypass the notification role as we want some events pinged where as others are just shown without notifying?

**Comment by BillyAB** [comment]
Hi,
This should be possible, leave it with me and I'll look to get it implemented.

**Comment by joeymisfit** [comment]
Thank you so much!

**Comment by BillyAB** [comment]
@joeymisfit This has now been implemented and can be downloaded in the latest release.
https://github.com/BillyAB/WHMCS-Discord-Notification-Module/releases/latest
